//
//  AppDelegate.swift
//  Generated by Servbiz. Safe to edit -- this is your project now.
//
//  UIKit with a plain window rather than SwiftUI, and no scene manifest.
//
//  WKWebView is a UIKit view. Wrapping it in SwiftUI means a
//  UIViewRepresentable, a Coordinator to hold the navigation delegate, and
//  @State plumbing to get at the things this shell actually needs -- the scroll
//  view's refresh control, the back/forward gesture, the status bar style. All of
//  that would be indirection around a view that is already a UIViewController's
//  natural content.
//

import UIKit

@main
final class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        let window = UIWindow(frame: UIScreen.main.bounds)

        // Not embedded in a UINavigationController. There is nothing to push: the
        // web view owns its own history, and a navigation bar would put a second
        // header above whatever header the site already draws.
        window.rootViewController = WebViewController()
        window.backgroundColor = AppConfig.backgroundColor

        self.window = window
        window.makeKeyAndVisible()
        return true
    }

    // Locks the app to the orientations chosen at build time.
    //
    // Enforced here as well as in Info.plist because UISupportedInterfaceOrientations
    // is advisory once a view controller overrides it, and this is the one place
    // that applies to every controller the app will ever present -- including the
    // media player iOS pushes for a fullscreen video.
    func application(
        _ application: UIApplication,
        supportedInterfaceOrientationsFor window: UIWindow?
    ) -> UIInterfaceOrientationMask {
        AppConfig.orientationMask
    }
}
