//
//  WebViewController.swift
//  Generated by Servbiz. Safe to edit -- this is your project now.
//
//  The whole app: one WKWebView showing your site, plus the handful of things
//  that make it behave like an app rather than a browser with no address bar.
//

import UIKit
import WebKit

final class WebViewController: UIViewController {

    private var webView: WKWebView!
    private var launchView: UIView?
    private var refreshControl: UIRefreshControl?
    private var launchTimeout: DispatchWorkItem?

    // MARK: - Setup

    override func loadView() {
        let config = WKWebViewConfiguration()

        // Without this every <video> takes over the whole screen on iPhone, which
        // is iOS's default and is rarely what a site embedding a small clip meant.
        config.allowsInlineMediaPlayback = AppConfig.inlineMedia

        // Empty set means nothing autoplays with sound, which is also the web
        // default. Left alone deliberately: an app that makes noise on launch is
        // worse than one that needs a tap.
        config.mediaTypesRequiringUserActionForPlayback = .all

        // A persistent data store is the reason the app stays signed in between
        // visits -- cookies and localStorage survive termination. This is the
        // default, and it is named here because it is load-bearing rather than
        // incidental: switching it to .nonPersistent() would silently sign the
        // customer out every launch.
        config.websiteDataStore = .default()

        webView = WKWebView(frame: .zero, configuration: config)
        webView.navigationDelegate = self
        webView.uiDelegate = self

        // An iPhone has no back button. Without the edge swipe, a customer who
        // taps into a page has no way back unless the site provides one.
        webView.allowsBackForwardNavigationGestures = AppConfig.swipeNavigation

        webView.allowsLinkPreview = AppConfig.allowsLinkPreview
        webView.backgroundColor = AppConfig.backgroundColor
        webView.scrollView.backgroundColor = AppConfig.backgroundColor

        // Stops the rubber-band overscroll revealing a white strip above a dark
        // site, which looks like a rendering fault.
        webView.scrollView.bounces = AppConfig.pullToRefresh

        view = webView
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        if AppConfig.respectSafeArea {
            // The web view fills the window; the *content* is inset. Inseting the
            // view itself would leave the safe areas as the window's background
            // colour, so a dark site would get light bars above and below.
            webView.scrollView.contentInsetAdjustmentBehavior = .always
        } else {
            webView.scrollView.contentInsetAdjustmentBehavior = .never
        }

        if AppConfig.pullToRefresh {
            let control = UIRefreshControl()
            control.addTarget(self, action: #selector(handleRefresh), for: .valueChanged)
            webView.scrollView.refreshControl = control
            refreshControl = control
        }

        if AppConfig.keepScreenOn {
            UIApplication.shared.isIdleTimerDisabled = true
        }

        showLaunchScreen()
        load(AppConfig.startURL)
    }

    // MARK: - Status bar

    override var preferredStatusBarStyle: UIStatusBarStyle {
        AppConfig.statusBarStyle
    }

    override var prefersStatusBarHidden: Bool {
        AppConfig.hideStatusBar
    }

    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        AppConfig.orientationMask
    }

    // MARK: - Loading

    private func load(_ url: URL) {
        webView.load(URLRequest(url: url))
    }

    @objc private func handleRefresh() {
        // reloadFromOrigin rather than reload: a cached page is exactly what
        // someone pulling to refresh is trying to get past.
        webView.reloadFromOrigin()
    }

    /// Covers the web view until the site has painted something.
    ///
    /// A launch screen that disappears on `didFinish` would still leave a flash of
    /// empty white on a slow connection, because `didFinish` fires when loading
    /// completes, not when pixels appear. The timeout is the safety net: a site
    /// that never finishes loading must not leave the customer staring at a
    /// splash screen forever.
    private func showLaunchScreen() {
        let cover = UIView(frame: view.bounds)
        cover.backgroundColor = AppConfig.splashColor
        cover.autoresizingMask = [.flexibleWidth, .flexibleHeight]

        if AppConfig.showLogo, let icon = UIImage(named: "LaunchLogo") {
            let imageView = UIImageView(image: icon)
            imageView.contentMode = .scaleAspectFit
            imageView.translatesAutoresizingMaskIntoConstraints = false
            cover.addSubview(imageView)
            NSLayoutConstraint.activate([
                imageView.centerXAnchor.constraint(equalTo: cover.centerXAnchor),
                imageView.centerYAnchor.constraint(equalTo: cover.centerYAnchor),
                imageView.widthAnchor.constraint(equalToConstant: 96),
                imageView.heightAnchor.constraint(equalToConstant: 96),
            ])
        } else {
            let spinner = UIActivityIndicatorView(style: .medium)
            spinner.translatesAutoresizingMaskIntoConstraints = false
            spinner.startAnimating()
            cover.addSubview(spinner)
            NSLayoutConstraint.activate([
                spinner.centerXAnchor.constraint(equalTo: cover.centerXAnchor),
                spinner.centerYAnchor.constraint(equalTo: cover.centerYAnchor),
            ])
        }

        view.addSubview(cover)
        launchView = cover

        let timeout = DispatchWorkItem { [weak self] in self?.hideLaunchScreen() }
        launchTimeout = timeout
        DispatchQueue.main.asyncAfter(
            deadline: .now() + AppConfig.splashMaxWait,
            execute: timeout
        )
    }

    private func hideLaunchScreen() {
        launchTimeout?.cancel()
        launchTimeout = nil
        guard let cover = launchView else { return }
        launchView = nil
        UIView.animate(withDuration: 0.22, animations: {
            cover.alpha = 0
        }, completion: { _ in
            cover.removeFromSuperview()
        })
    }

    // MARK: - Errors

    /// Shown when the site cannot be reached at all.
    ///
    /// A web view that fails to load shows a blank white screen with no
    /// explanation, which reads as a broken app rather than a missing network.
    private func showOfflineNotice() {
        hideLaunchScreen()

        let notice = UIView(frame: view.bounds)
        notice.backgroundColor = AppConfig.splashColor
        notice.autoresizingMask = [.flexibleWidth, .flexibleHeight]

        let label = UILabel()
        label.text = "Can\u{2019}t connect right now.\nCheck your internet connection."
        label.numberOfLines = 0
        label.textAlignment = .center
        label.textColor = .secondaryLabel
        label.font = .preferredFont(forTextStyle: .body)
        // So the message grows with the customer's text-size setting.
        label.adjustsFontForContentSizeCategory = true
        label.translatesAutoresizingMaskIntoConstraints = false

        let button = UIButton(type: .system)
        button.setTitle("Try again", for: .normal)
        button.addTarget(self, action: #selector(retry), for: .touchUpInside)
        button.translatesAutoresizingMaskIntoConstraints = false

        notice.addSubview(label)
        notice.addSubview(button)
        NSLayoutConstraint.activate([
            label.centerXAnchor.constraint(equalTo: notice.centerXAnchor),
            label.centerYAnchor.constraint(equalTo: notice.centerYAnchor, constant: -20),
            label.leadingAnchor.constraint(greaterThanOrEqualTo: notice.leadingAnchor, constant: 32),
            label.trailingAnchor.constraint(lessThanOrEqualTo: notice.trailingAnchor, constant: -32),
            button.centerXAnchor.constraint(equalTo: notice.centerXAnchor),
            button.topAnchor.constraint(equalTo: label.bottomAnchor, constant: 16),
        ])

        view.addSubview(notice)
        launchView = notice
    }

    @objc private func retry() {
        hideLaunchScreen()
        showLaunchScreen()
        load(AppConfig.startURL)
    }
}

// MARK: - Navigation

extension WebViewController: WKNavigationDelegate {

    /// Decides what opens in the app and what leaves it.
    ///
    /// The allow-list is the security boundary of this shell. Without it, a link
    /// or an injected redirect could point the app at any page at all, and it
    /// would render inside an app carrying the customer's name and holding their
    /// logged-in session cookies.
    func webView(
        _ webView: WKWebView,
        decidePolicyFor navigationAction: WKNavigationAction,
        decisionHandler: @escaping (WKNavigationActionPolicy) -> Void
    ) {
        guard let url = navigationAction.request.url else {
            decisionHandler(.cancel)
            return
        }

        // tel:, mailto:, sms:, maps: and the like. Handed to the system, which is
        // the only thing that can act on them.
        if let scheme = url.scheme?.lowercased(), !["http", "https"].contains(scheme) {
            UIApplication.shared.open(url)
            decisionHandler(.cancel)
            return
        }

        if AppConfig.isAllowedHost(url) {
            decisionHandler(.allow)
            return
        }

        // Off-site. Opened in Safari when configured, otherwise refused outright
        // -- never rendered in here.
        if AppConfig.externalLinksInBrowser {
            UIApplication.shared.open(url)
        }
        decisionHandler(.cancel)
    }

    func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        hideLaunchScreen()
        refreshControl?.endRefreshing()
    }

    func webView(
        _ webView: WKWebView,
        didFail navigation: WKNavigation!,
        withError error: Error
    ) {
        refreshControl?.endRefreshing()
        handle(error)
    }

    func webView(
        _ webView: WKWebView,
        didFailProvisionalNavigation navigation: WKNavigation!,
        withError error: Error
    ) {
        refreshControl?.endRefreshing()
        handle(error)
    }

    private func handle(_ error: Error) {
        let code = (error as NSError).code
        // -999 is "cancelled", which is what a redirect or a fast second tap
        // produces. Showing an offline screen for it would flash an error over a
        // page that is loading perfectly well.
        if code == NSURLErrorCancelled { return }

        // Anything already on screen is better than an error over it: a failed
        // sub-resource or a failed back-navigation should not blank the page the
        // customer is reading.
        if webView.url != nil && !webView.isLoading && launchView == nil { return }

        showOfflineNotice()
    }
}

// MARK: - UI

extension WebViewController: WKUIDelegate {

    /// target="_blank" and window.open().
    ///
    /// Returning nil would make those links do nothing at all, which is the
    /// default and a common complaint about web-view apps. Loading them in the
    /// same view is right for an app with no tabs.
    func webView(
        _ webView: WKWebView,
        createWebViewWith configuration: WKWebViewConfiguration,
        for navigationAction: WKNavigationAction,
        windowFeatures: WKWindowFeatures
    ) -> WKWebView? {
        if let url = navigationAction.request.url {
            if AppConfig.isAllowedHost(url) {
                webView.load(URLRequest(url: url))
            } else if AppConfig.externalLinksInBrowser {
                UIApplication.shared.open(url)
            }
        }
        return nil
    }

    // JavaScript dialogs. WKWebView shows nothing for these unless the host app
    // implements them, so a site relying on confirm() to guard a destructive
    // action would otherwise have that guard silently vanish.

    func webView(
        _ webView: WKWebView,
        runJavaScriptAlertPanelWithMessage message: String,
        initiatedByFrame frame: WKFrameInfo,
        completionHandler: @escaping () -> Void
    ) {
        let alert = UIAlertController(title: nil, message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "OK", style: .default) { _ in completionHandler() })
        present(alert, animated: true)
    }

    func webView(
        _ webView: WKWebView,
        runJavaScriptConfirmPanelWithMessage message: String,
        initiatedByFrame frame: WKFrameInfo,
        completionHandler: @escaping (Bool) -> Void
    ) {
        let alert = UIAlertController(title: nil, message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "Cancel", style: .cancel) { _ in completionHandler(false) })
        alert.addAction(UIAlertAction(title: "OK", style: .default) { _ in completionHandler(true) })
        present(alert, animated: true)
    }

    func webView(
        _ webView: WKWebView,
        runJavaScriptTextInputPanelWithPrompt prompt: String,
        defaultText: String?,
        initiatedByFrame frame: WKFrameInfo,
        completionHandler: @escaping (String?) -> Void
    ) {
        let alert = UIAlertController(title: nil, message: prompt, preferredStyle: .alert)
        alert.addTextField { $0.text = defaultText }
        alert.addAction(UIAlertAction(title: "Cancel", style: .cancel) { _ in completionHandler(nil) })
        alert.addAction(UIAlertAction(title: "OK", style: .default) { _ in
            completionHandler(alert.textFields?.first?.text)
        })
        present(alert, animated: true)
    }
}
